### ISSUE TITLE
Adding a meaningful title to each page

### ISSUE THREAD

**Issue by adulau** [cedricbonhomme/Freshermeat#5]
Adding a meaningful title to each page would be great to map the content of each pages.

**Comment by cedricbonhomme** [comment]
Good idea. I'll do that.

For your information I started to test http://ogp.me/ : 
https://github.com/cedricbonhomme/Freshermeat/blob/master/src/web/templates/index.html#L4
I'll also set these attributes per projects pages.

**Comment by cedricbonhomme** [comment]
Done for most of the pages. I will also add titles for others relevant pages.
