### ISSUE TITLE
CC-0 and Public domain are missing as license

### ISSUE THREAD

**Issue by adulau** [cedricbonhomme/Freshermeat#6]
CC-0 and Public domain are missing as license

**Comment by adulau** [comment]
Found the data management UI ;-) Maybe we need to add it in the default list.

**Comment by cedricbonhomme** [comment]
For your information I initialised the database of licenses with:
https://spdx.org/licenses/licenses.json
(https://github.com/cedricbonhomme/Freshermeat/blob/master/src/manager.py#L95)

But yes it is possible to add the ones that are missing with the simple UI of Flask-Admin :-)
