### ISSUE TITLE
Creating an org and project based on a single GitHub link

### ISSUE THREAD

**Issue by adulau** [cedricbonhomme/Freshermeat#7]
Creating an org and project based on a single GitHub link. I suppose this would be possible.

**Comment by cedricbonhomme** [comment]
yep, certainly via a bookmarklet.

**Comment by cedricbonhomme** [comment]
It is now possible to create a project thanks to a bookmarklet 7e9408d304b6f574008a2cc0f243fd4dca2638de

This is actually not working on GitHub with Firefox (https://blog.github.com/2013-04-19-content-security-policy/). I'll try another solution maybe with the GitHub API (even if I do not want too much links with GitHub API).
I just discovered that the pinboard.in bookmarklet is also not working on GitHub.

**Comment by cedricbonhomme** [comment]
almost done. It works with the API of GitHub. I just have to edit some template for the web pages...

**Comment by cedricbonhomme** [comment]
Done :-)
I''ll deploy it, it requires a new variable in the configuration file.

**Comment by adulau** [comment]
Cool! Thank you very much.

**Comment by cedricbonhomme** [comment]
You're welcome!
Deployed and tested :-)
You can use the form in the navbar, or:

`GET https://open-source-security-software.net/project/import/github?repo=https://github.com/mseclab/nathan`
for example. I just imported this project...

And I just realized that I have to improve the UI of the form in the navbar. Not a good layout on this screen...
